#!/usr/bin/env python3
"""Sales intelligence app — prospect list for a cybersecurity vendor.

Reads a precomputed Parquet and nothing else. No database, no API key, no
inference at request time: every classification, score and finding was decided
in the pipeline. The app filters and explains.

It is built around the three questions a rep actually needs answered before
picking up the phone — why this account, why now, and what do I say — rather
than around the shape of the underlying data.

Outreach text is assembled from templates, not generated by a model at request
time. That is a deliberate constraint: it keeps the deployment credential-free
and makes every sentence auditable. The tone and format controls therefore
select between template families rather than reprompting.
"""

from __future__ import annotations

from pathlib import Path
from typing import NamedTuple

import pandas as pd
import streamlit as st


class Finding(NamedTuple):
    """One observable finding, in the forms the UI needs.

    `label` and `detail` fill a table cell, where the column header supplies
    context. `phrase` is for prose, where it cannot — "1 host" is meaningful
    under a "Detail" column and meaningless mid-sentence.

    `severity` drives the badge colour only. It ranks how alarming a finding is
    to a rep, which is not the same as how exploitable it is — that is what
    EPSS is for, and it stays in the detail table.
    """

    label: str
    detail: str
    evidence: str   # observed | tested | inferred
    phrase: str
    severity: str   # critical | high | medium


class Brief(NamedTuple):
    """Everything needed to write one piece of outreach.

    Bundled rather than passed as four arguments: format and tone are chosen
    together in the UI and travel together into every template.
    """

    row: object
    signals: list[Finding]
    fmt: str
    tone: str


DATA = Path(__file__).parent / "data" / "accounts.parquet"

TIER_HELP = {
    "A - call now": "Strong ICP fit and an urgent, current finding.",
    "B - nurture": "Good fit, nothing urgent. Sequence, don't call.",
    "C - opportunistic": "Urgent finding, weaker fit. Worth a look.",
    "D - deprioritise": "Neither fit nor urgency.",
    "R - needs review": "Classified as a company, but below the confidence "
                        "threshold. A human should confirm before outreach.",
}

# Foreground, background, glyph. Light backgrounds with dark text stay legible
# under both Streamlit themes, which a theme-coloured badge does not.
BADGE_STYLE = {
    "critical": ("#7f1d1d", "#fecaca", "🚩"),
    "high":     ("#78350f", "#fde68a", "⚠️"),
    "medium":   ("#1e3a5f", "#bfdbfe", "◆"),
    "context":  ("#374151", "#e5e7eb", "•"),
}

FORMATS = ["Cold email", "LinkedIn InMail", "Call script"]
TONES = ["Urgent / technical", "Consultative / executive"]

st.set_page_config(page_title="Sales Intelligence", page_icon="◆", layout="wide")


@st.cache_data
def load() -> pd.DataFrame:
    return pd.read_parquet(DATA)


def count(n: int, singular: str, plural: str | None = None) -> str:
    """'1 host' / '4 hosts'. The '1 host(s)' construction reads as unfinished
    text, and an opener that looks unfinished does not get sent."""
    return f"{n} {singular if n == 1 else (plural or singular + 's')}"


def epss_phrase(probability: float, precise: bool = False) -> str:
    """EPSS as a percentage, never rounded up to a certainty.

    EPSS tops out around 0.9997, which `:.0%` renders as "100%". Telling a
    prospect a vulnerability has a 100% chance of exploitation is an overclaim
    that undoes the hedging everywhere else, and it is the first thing a
    technical buyer will push back on.
    """
    if probability >= 0.995:
        return ">99%"
    if probability < 0.01:
        return "<1%"
    return f"{probability:.1%}" if precise else f"{probability:.0%}"


def signal_rows(row) -> list[Finding]:
    """Observable findings for one account, worst first.

    Each finding carries three text forms: a short label and a detail for the
    table, and a prose phrase for outreach. They differ because a table cell can
    rely on its column header for context and a sentence cannot — "1 host" means
    nothing mid-sentence without the finding it belongs to.

    `evidence` separates what was directly observed from what was inferred from
    a version banner. The two carry very different weight on a call, and
    collapsing them is how a rep ends up asserting a vulnerability that was
    never confirmed.
    """
    out: list[Finding] = []
    add = out.append

    if row.n_exposed_datastores:
        n = int(row.n_exposed_datastores)
        add(Finding("Exposed database",
                    f"{count(n, 'database')} reachable from the public internet",
                    "observed",
                    f"{count(n, 'database')} reachable from the public internet",
                    "critical"))
    if row.n_remote_access:
        n = int(row.n_remote_access)
        add(Finding("Remote access exposed",
                    f"{count(n, 'service')} — telnet, RDP, VNC, FTP or SMB",
                    "observed",
                    f"{count(n, 'remote-access service')} open to the internet",
                    "critical"))
    if row.heartbleed_vulnerable:
        add(Finding("Heartbleed", "Failed a direct vulnerability probe", "tested",
                    "a host failing a direct Heartbleed probe", "critical"))
    if row.n_exposed_cameras:
        n = int(row.n_exposed_cameras)
        add(Finding("Exposed cameras", f"{count(n, 'camera interface')} reachable",
                    "observed", f"{count(n, 'IP camera interface')} publicly reachable",
                    "critical"))
    if row.n_open_directories:
        n = int(row.n_open_directories)
        add(Finding("Open directory listing", count(n, "host"), "observed",
                    f"directory listings exposed on {count(n, 'host')}", "high"))
    if row.n_expired_certs:
        n = int(row.n_expired_certs)
        add(Finding("Expired certificate", f"{count(n, 'host')} serving an expired cert",
                    "observed", f"{count(n, 'host')} serving an expired certificate",
                    "high"))
    if pd.notna(row.soonest_cert_expiry_days) and 0 <= row.soonest_cert_expiry_days <= 30:
        d = int(row.soonest_cert_expiry_days)
        add(Finding("Certificate expiring", f"In {count(d, 'day')}", "observed",
                    f"a certificate expiring in {count(d, 'day')}", "medium"))
    if row.n_eol_services:
        n = int(row.n_eol_services)
        add(Finding("End-of-life software", f"{count(n, 'service')} past vendor support",
                    "observed", f"{count(n, 'service')} running software past vendor support",
                    "high"))
    if row.n_dead_ssl:
        n = int(row.n_dead_ssl)
        add(Finding("SSLv2/SSLv3 accepted", count(n, "host"), "observed",
                    f"{count(n, 'host')} still accepting SSLv2 or SSLv3", "high"))
    if row.n_deprecated_tls:
        n = int(row.n_deprecated_tls)
        add(Finding("TLS 1.0/1.1 accepted", f"{count(n, 'host')} — a PCI-DSS finding",
                    "observed",
                    f"{count(n, 'host')} still accepting TLS 1.0 or 1.1, which is a "
                    "PCI-DSS finding", "medium"))
    if row.n_self_signed:
        n = int(row.n_self_signed)
        add(Finding("Self-signed certificate", count(n, "host"), "observed",
                    f"{count(n, 'host')} serving a self-signed certificate", "medium"))
    if row.n_weak_cert_sig:
        n = int(row.n_weak_cert_sig)
        add(Finding("SHA-1 certificate signature", count(n, "host"), "observed",
                    f"{count(n, 'certificate')} still signed with SHA-1", "medium"))
    if pd.notna(row.max_epss) and row.max_epss > 0:
        cvss = (f" — CVSS {row.headline_cve_cvss:.1f}"
                if pd.notna(row.headline_cve_cvss) else "")
        add(Finding(str(row.headline_cve),
                    f"{epss_phrase(row.max_epss, precise=True)} chance of "
                    f"exploitation within 30 days{cvss}",
                    "inferred",
                    f"software associated with {row.headline_cve}, which carries a "
                    f"{epss_phrase(row.max_epss)} probability of exploitation in the "
                    f"next 30 days",
                    "high" if row.max_epss > 0.10 else "medium"))
    return out


def badge(text: str, kind: str) -> str:
    """One inline badge as HTML.

    HTML rather than Streamlit's coloured-text markdown because that syntax
    arrived in a recent version and this app is deployed against whatever
    Community Cloud resolves.
    """
    fg, bg, glyph = BADGE_STYLE[kind]
    return (f"<span style='background:{bg};color:{fg};padding:3px 9px;"
            f"border-radius:11px;font-size:0.79rem;font-weight:600;"
            f"white-space:nowrap;display:inline-block;margin:0 5px 6px 0'>"
            f"{glyph} {text}</span>")


def context_badges(row) -> list[tuple[str, str]]:
    """Commercial context, as distinct from security findings.

    These say who the account is rather than what is wrong with it, so they are
    styled neutrally — a rep should not read "Public sector" with the same
    urgency as "Exposed database".
    """
    out = []
    if row.entity_class == "government_or_education":
        out.append(("Public sector", "context"))
    if row.no_waf_anywhere:
        out.append(("No incumbent WAF", "context"))
    if pd.notna(row.n_countries) and row.n_countries > 1:
        out.append((f"{int(row.n_countries)} markets", "context"))
    if pd.notna(row.publishes_securitytxt) and row.publishes_securitytxt:
        out.append(("Publishes security.txt", "context"))
    return out


def render_badges(row, signals) -> None:
    """Findings first, ordered by severity, then commercial context."""
    rank = {"critical": 0, "high": 1, "medium": 2}
    items = [(f.label, f.severity) for f in sorted(signals, key=lambda f: rank[f.severity])]
    items += context_badges(row)
    if not items:
        st.caption("No findings and no distinguishing context.")
        return
    st.markdown("".join(badge(t, k) for t, k in items), unsafe_allow_html=True)


def _clauses(brief: Brief) -> tuple[str, str]:
    """The observed and inferred sentences, phrased for the chosen tone.

    The inferred sentence deliberately does not name the product alongside the
    CVE. Both are aggregated per entity by highest EPSS, but potentially from
    different services on the same host — so "you are running Apache, which is
    vulnerable to <CVE>" can pair a web server with a glibc bug. Observed once
    in testing: Apache httpd against CVE-2015-0235 (GHOST). A wrong technical
    claim in a first email is worse than a vaguer true one.
    """
    row, signals = brief.row, brief.signals
    observed = [f for f in signals if f.evidence in ("observed", "tested")]
    inferred = [f for f in signals if f.evidence == "inferred"]
    technical = brief.tone == TONES[0]

    seen = ""
    if observed and technical:
        rest = f", and {observed[1].phrase}" if len(observed) > 1 else ""
        seen = (f"On {row.company}'s public infrastructure we can currently see "
                f"{observed[0].phrase}{rest}. That's visible to anyone scanning, "
                f"not just us.")
    elif observed:
        seen = (f"A quick look at {row.company}'s public-facing estate shows "
                f"{observed[0].phrase} — the kind of thing that tends to surface "
                f"in a customer security review or an insurance renewal before "
                f"it surfaces internally.")

    risk = ""
    if inferred and technical:
        risk = (f"Separately, one of your public hosts is running a software "
                f"version associated with {row.headline_cve} — currently around a "
                f"{epss_phrase(row.max_epss)} chance of being exploited in the next "
                f"30 days. That one is inferred from a version banner rather than "
                f"tested, so it's worth confirming whether it actually applies.")
    elif inferred:
        risk = (f"There is also a software version in your estate linked to a "
                f"vulnerability with a {epss_phrase(row.max_epss)} chance of active "
                f"exploitation this month. We infer that from a version banner "
                f"rather than testing it, so treat it as a question rather than "
                f"a finding.")
    return seen, risk


def _cold_email(brief: Brief) -> str:
    seen, risk = _clauses(brief)
    row = brief.row
    technical = brief.tone == TONES[0]

    lead = brief.signals[0].label if brief.signals else "internet-facing exposure"
    subject = (f"Subject: {lead} on {row.entity_domain}" if technical
               else f"Subject: Quick note on {row.company}'s external exposure")

    parts = [subject, ""]
    parts.append(f"Hi — we track internet-facing exposure across "
                 f"{row.primary_country_name}.")
    parts += [p for p in (seen, risk) if p]
    parts.append("Happy to walk through the detail on a short call if useful."
                 if technical else
                 "If it's useful I can send the full picture over, no call needed.")
    return "\n\n".join(parts)


def _linkedin(brief: Brief) -> str:
    """Shorter, no subject line, no second finding — InMail is read on a phone."""
    seen, risk = _clauses(brief)
    row = brief.row
    body = seen or risk
    if not body:
        return (f"Hi — we map internet-facing exposure for organisations in "
                f"{row.primary_country_name}. Nothing urgent on {row.company} "
                f"right now, but happy to share what we can see if useful.")

    closing = ("Worth a 15-minute look?" if brief.tone == TONES[0]
               else "Would it be useful if I sent that across?")
    return f"Hi — we map internet-facing exposure in {row.primary_country_name}. " \
           f"{body} {closing}"


def _call_script(brief: Brief) -> str:
    """Structured prompts rather than prose — nobody reads a paragraph aloud."""
    seen, risk = _clauses(brief)
    row = brief.row
    signals = brief.signals

    lines = [
        f"OPEN — \"Hi, calling from [vendor]. We map internet-facing exposure "
        f"for organisations in {row.primary_country_name}. Is now a bad time?\"",
        "",
        "REASON FOR THE CALL",
    ]
    lines.append(f"  · {seen}" if seen else
                 f"  · No observed finding — lead with the ICP fit "
                 f"({int(row.n_hosts)} hosts, {int(row.n_ports)} open ports).")
    if risk:
        lines += ["", "IF THEY ASK WHAT ELSE", f"  · {risk}"]

    lines += ["", "PROOF POINTS — all checkable, no login required"]
    lines += [f"  · {f.label}: {f.detail}  [{f.evidence}]" for f in signals[:4]]

    lines += [
        "",
        "QUESTION — \"Who owns external attack surface for you today, and how "
        "are they finding this sort of thing?\"",
        "",
        "IF \"WE ALREADY HAVE A VENDOR\"",
        "  · \"Understood — we found this from the outside with no access. "
        "Worth checking whether it's in their scope.\"" if row.no_waf_anywhere else
        "  · \"Understood — worth comparing what they report against what's "
        "externally visible.\"",
    ]
    return "\n".join(lines)


WRITERS = {
    FORMATS[0]: _cold_email,
    FORMATS[1]: _linkedin,
    FORMATS[2]: _call_script,
}


def outreach(brief: Brief) -> str:
    """Assemble outreach for the chosen format and tone.

    Every sentence traces to a finding in the table above it. Version-inferred
    findings are hedged explicitly: the product and version are observed facts,
    the vulnerability is a possibility, and leading with "you have 99
    vulnerabilities" is usually wrong and costs the rep the call.
    """
    if not brief.signals and brief.fmt != FORMATS[2]:
        return (f"No specific finding to lead with for {brief.row.company}. "
                f"Use the call script format, which leads on fit instead.")
    return WRITERS[brief.fmt](brief)


def crm_columns(frame: pd.DataFrame) -> pd.DataFrame:
    """The prospect list as a CRM would want it: named columns, no scores the
    importing system cannot interpret, and the domain as the join key."""
    cols = {
        "company": "Company", "entity_domain": "Domain", "tier": "Tier",
        "intent_score": "Urgency", "fit_score": "Fit",
        "primary_country_name": "Market", "primary_city": "City",
        "n_hosts": "Hosts", "n_ports": "Open ports",
        "max_epss": "Exploit probability", "headline_cve": "Top CVE",
        "no_waf_anywhere": "Whitespace", "entity_class": "Classification",
        "class_confidence": "Classification confidence",
    }
    present = [c for c in cols if c in frame.columns]
    return frame[present].rename(columns=cols)


df = load()

# ---------------------------------------------------------------- sidebar
st.sidebar.title("Filters")
st.sidebar.caption("Territory and segment, the way a rep works a list.")

tiers = sorted(t for t in df.tier.unique() if not t.startswith(("X", "U")))
tier_sel = st.sidebar.multiselect("Tier", tiers,
                                  default=[t for t in tiers if t.startswith("A")] or tiers)

markets = sorted(df.primary_country_name.dropna().unique())
market_sel = st.sidebar.multiselect("Market", markets, default=[])

# Public sector dominates the ranking — universities and research institutes
# run large, old, heterogeneous estates, so they accumulate findings. They are
# genuine buyers but a different motion: procurement and tenders, not a cold
# call. Separated so a rep can work one or the other, not a mixed list.
segment = st.sidebar.radio(
    "Segment", ["All", "Commercial only", "Public sector only"], index=1,
    help="Public sector means universities, government bodies and schools.")

size_bands = {"Any": (0, 10**9), "1 host": (1, 1), "2–10": (2, 10),
              "11–100": (11, 100), "101–500": (101, 500), "500+": (501, 10**9)}
size_sel = st.sidebar.selectbox("Estate size", list(size_bands), index=0)

min_intent = st.sidebar.slider("Minimum urgency", 0, 100, 0, 5)
whitespace_only = st.sidebar.checkbox(
    "Whitespace only", help="No WAF anywhere — no incumbent vendor to displace.")
actively_exploited = st.sidebar.checkbox(
    "Actively exploited only", help="A vulnerability with EPSS above 10%.")

view = df[df.tier.isin(tier_sel)] if tier_sel else df
if segment == "Commercial only":
    view = view[view.entity_class == "end_customer_company"]
elif segment == "Public sector only":
    view = view[view.entity_class == "government_or_education"]
if market_sel:
    view = view[view.primary_country_name.isin(market_sel)]
low, high = size_bands[size_sel]
view = view[(view.n_hosts >= low) & (view.n_hosts <= high)]
view = view[view.intent_score >= min_intent]
if whitespace_only:
    view = view[view.no_waf_anywhere]
if actively_exploited:
    view = view[view.max_epss.fillna(0) > 0.10]

view = view.sort_values(["intent_score", "fit_score"], ascending=False)

# ---------------------------------------------------------------- header
st.title("Sales intelligence")
st.caption("Companies with internet-facing security exposure, ranked by how "
           "urgently they need help and how well they fit the ICP.")

c1, c2, c3, c4 = st.columns(4)
c1.metric("Accounts in view", f"{len(view):,}")
c2.metric("Call now", f"{(view.tier == 'A - call now').sum():,}")
c3.metric("Whitespace", f"{view.no_waf_anywhere.sum():,}",
          help="No perimeter vendor detected anywhere in the estate")
c4.metric("Actively exploited", f"{(view.max_epss.fillna(0) > 0.10).sum():,}",
          help="Carrying a vulnerability with EPSS above 10%")

if view.empty:
    st.info("No accounts match these filters.")
    st.stop()

# ---------------------------------------------------------------- list
st.subheader("Prospect list")
st.dataframe(
    view[["company", "tier", "intent_score", "fit_score", "primary_country_name",
          "n_hosts", "max_epss", "headline_cve", "no_waf_anywhere"]]
    .rename(columns={
        "company": "Company", "tier": "Tier", "intent_score": "Urgency",
        "fit_score": "Fit", "primary_country_name": "Market", "n_hosts": "Hosts",
        "max_epss": "Exploit prob.", "headline_cve": "Top CVE",
        "no_waf_anywhere": "Whitespace"}),
    use_container_width=True, hide_index=True, height=340,
    column_config={
        "Exploit prob.": st.column_config.ProgressColumn(
            format="%.0f%%", min_value=0, max_value=1),
        "Urgency": st.column_config.NumberColumn(format="%d"),
        "Fit": st.column_config.NumberColumn(format="%d")},
)

st.download_button(
    "⬇  Export prospect list to CSV",
    crm_columns(view).to_csv(index=False).encode("utf-8"),
    file_name=f"prospects-{len(view)}-accounts.csv",
    mime="text/csv",
    help="The filtered list as shown, with the domain as the CRM join key.")

# ---------------------------------------------------------------- detail
st.divider()
choice = st.selectbox("Account detail", view.entity_domain.tolist(),
                      format_func=lambda d: f"{view.set_index('entity_domain').loc[d, 'company']}  ·  {d}")
row = view.set_index("entity_domain").loc[choice]
signals = signal_rows(row)

st.header(row.company)
st.caption(f"{choice}  ·  {row.primary_city or ''} {row.primary_country_name or ''}  ·  "
           f"{int(row.n_hosts)} hosts, {int(row.n_ports)} open ports")
render_badges(row, signals)

left, right = st.columns([2, 1])

with left:
    st.subheader("Why now")
    if signals:
        with st.expander("Finding detail and evidence", expanded=True):
            st.dataframe(pd.DataFrame([(f.label, f.detail, f.evidence) for f in signals],
                                      columns=["Finding", "Detail", "Evidence"]),
                         use_container_width=True, hide_index=True)
            st.caption("**observed** — seen directly in the scan.  "
                       "**tested** — confirmed by an active probe.  "
                       "**inferred** — implied by a version banner; the software "
                       "is confirmed, the vulnerability is not.")
    else:
        st.write("No specific findings.")

    st.subheader("What to say")
    f1, f2 = st.columns(2)
    fmt = f1.selectbox("Format", FORMATS,
                       help="Length and structure change; the findings do not.")
    tone = f2.selectbox("Tone", TONES,
                        help="Technical names the protocols and probabilities. "
                             "Executive leads on business consequence.")

    text = outreach(Brief(row, signals, fmt, tone))
    st.text_area("Draft", text, height=290, label_visibility="collapsed")

    with st.expander("📋  Copy-ready — click the icon in the corner"):
        st.code(text, language=None)

    st.caption("Assembled from the findings above using templates, not written "
               "by a model at request time. Every claim traces to a row in the "
               "table; inferred findings are hedged in the text.")

with right:
    st.subheader("Why this account")
    st.metric("Urgency", int(row.intent_score))
    st.metric("Fit", int(row.fit_score))
    st.write(f"**{row.tier}**")
    st.caption(TIER_HELP.get(row.tier, ""))

    st.write("**Score drivers**")
    drivers = [
        ("Exploitation probability", row.pts_epss),
        ("Critical CVE", row.pts_critical_cve),
        ("Exposed datastore", row.pts_datastore),
        ("Remote access", row.pts_remote_access),
        ("End-of-life software", row.pts_eol),
        ("Certificate expired", row.pts_expired_cert),
        ("Estate size band", row.pts_size_band),
        ("No incumbent vendor", row.pts_whitespace),
        ("Multi-market", row.pts_multi_country),
    ]
    for label, points in drivers:
        if points:
            st.write(f"`+{int(points):>2}`  {label}")

    st.write("**Classification**")
    st.caption(f"{row.entity_class} · confidence {row.class_confidence:.2f}")
    st.caption(f"_{row.class_reasoning}_")
    if row.tier.startswith("R"):
        st.warning("Below the confidence threshold — confirm before outreach.")

st.divider()
st.caption(
    "Every classification, score and finding is precomputed. This app performs "
    "no inference and holds no credentials. Vulnerability findings are inferred "
    "from version banners unless marked observed or tested."
)
